project:
  type: website
  output-dir: docs


lang: en
website:
  title: "Open Science and Reproducibility with Quarto, GitHub, and R"
  site-url: https://e-kotov.github.io/2024-EDSD-open-science-quarto-github/
  repo-url: https://github.com/e-kotov/2024-EDSD-open-science-quarto-github
  page-navigation: true
  page-footer: 
      border: true
      left: "License [CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/){target='_blank'}"
      right: 
        - icon: github
          href: https://github.com/e-kotov/2024-EDSD-open-science-quarto-github

  sidebar:
    style: "docked"
    search: true
    tools: 
      - icon: github
        text: Github
        href: https://github.com/e-kotov/2024-EDSD-open-science-quarto-github
      - icon: twitter
        text: twitter
        href: https://x.com/MPIDRnews
    contents:
      - index.qmd
      - 00-setup.qmd
      - href: questions.qmd
        text: "0b. Questions during the workshop"
      - task-01.qmd



format:
  html:
    include-in-header:
        file: analytics.html
    theme:
      light: zephyr
      dark: slate
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 4
    toc-location: right
    code-overflow: wrap
    grid:
      body-width: 800px
    mermaid:
      theme: neutral

bibliography: references.bib
bibliographystyle: mla

editor: source

editor_options:
  markdown:
    wrap: 72
    canonical: true

execute:
  freeze: auto
